- src/useStyleRegister.tsx
- tests/util.spec.tsx
FIX:
```less
@media (max-width: 12450px) {
.btn {
color: red;
}
}
```
to be
```less
.hashed@media (max-width: 12450px) {
.btn {
color: red;
}
}
```
which should be
```less
@media (max-width: 12450px) {
.hashed.btn {
color: red;
}
}
```
> fix: Media query should pass query to children

- jest.config.js
- package.json
- src/useStyleRegister.tsx
- tests/animation.spec.tsx
- tests/index.spec.tsx
- tests/server.spec.tsx
- tests/setupAfterEnv.js
- tests/style.spec.tsx
保持结构一致性，以防止 ssr sticky mode 下导致的 useId 变化。
> fix: Compatible for useId with React 18

- src/useCacheToken.tsx
- tests/index.spec.tsx
让开发者在开发环境如果复写 hash 样式在生产环境不会生效以协助用户不要去尝试通过覆盖 hash 达到覆盖样式效果。
> refactor: patch diff hash in dev

- docs/demo/seed.md
- docs/examples/components/theme.tsx
- docs/examples/seed.tsx
- docs/examples/theme.tsx
- src/Theme.ts
- src/index.ts
- src/useCacheToken.tsx
- tests/theme.spec.tsx
Enable theme as part of token cache.
> feat: support createTheme for cache

- docs/examples/basic.less
- docs/examples/basic.tsx
- src/StyleContext.tsx
- src/useStyleRegister.tsx
- tests/index.spec.tsx
调整时序，让 cssinjs 总是添加到 header 最前面以降低其相对于 app override style 的优先级。
resolve https://github.com/ant-design/ant-design/issues/36742
> fix: override order

- src/transformers/legacyLogicalProperties.ts
- tests/transform.spec.tsx
split 本来是为了这种情况存在的：`paddingInline: 2px 4px` 会转换成 `paddingLeft: 2px; paddingRight: 4px`。
简单的 `split(/\s+/)` 会将 `calc` 错误地分离。
其实还有更复杂的情况，比如圆角会有用 `/` 的情况。antd 中没有遇到，有问题再处理。
close https://github.com/ant-design/ant-design/issues/39881
close https://github.com/ant-design/ant-design/issues/39882
> fix: css transformer should not split calc

- src/StyleContext.tsx
- src/hooks/useStyleRegister.tsx
- src/index.ts
- src/linters/contentQuotesLinter.ts
- src/linters/hashedAnimationLinter.ts
- src/linters/index.ts
- src/linters/interface.ts
- src/linters/logicalPropertiesLinter.ts
- src/linters/utils.ts
- src/util.ts
- tests/linter.spec.tsx
linter 模块化，由于 logical properties 的检查并不是必要的，抽离之后由需要的引入。
`content` 和 `animation` 的检查内置。
close https://github.com/ant-design/cssinjs/issues/71
> feat: StyleProvider support `linters`

- src/transformers/legacyLogicalProperties.ts
- tests/transform.spec.tsx
fix https://github.com/ant-design/ant-design/issues/40986
> fix: important should also convert

- src/hooks/useStyleRegister.tsx
- tests/index.spec.tsx
ref https://github.com/ant-design/ant-design/issues/40355
> feat: support nonce

- package.json
- src/hooks/useGlobalCache.tsx
- tests/index.spec.tsx
Origin counter is increased in `useMemo` and clear in `useEffect`.
In Suspense mode, component may call `useMemo` multiple times, which may not align with `useEffect` times. Let's all move counter into `useEffect` instead.
> fix: Suspense will make cache counter not sync

- src/hooks/useCompatibleInsertionEffect.tsx
- src/hooks/useGlobalCache.tsx
- src/hooks/useInsertionEffect.tsx
- tests/legacy.spec.tsx
- fix: should not race with useLayoutEffect
- chore: optimize
- chore: add test case
- chore: rename
> fix: should not race with useLayoutEffect

- src/hooks/useCacheToken.tsx
- src/hooks/useCompatibleInsertionEffect.tsx
- src/hooks/useGlobalCache.tsx
- tests/legacy.spec.tsx
由于新渲染的组件 render 阶段要比旧组件的 unmount 阶段更早，所以在 react 17 以下会出现先插入新组件的 style 标签，再执行旧组件的卸载，最后执行新组件的 mount，计数+1。在旧组件卸载时计数实际上还没有增加，所以就回触发删除逻辑。
ref: https://codesandbox.io/s/aged-cdn-qjxmpz?file=/src/App.tsx
> fix: style should regenerate when remounted

- src/hooks/useStyleRegister/cacheMapUtil.ts
- tests/server.spec.tsx
如果样式已经移除，则清理 cacheMap 以优化页面来回切换时不必要的损耗。
> enhance: clean cache if not exist anymore

- src/hooks/useStyleRegister/index.tsx
- tests/server.spec.tsx
close https://github.com/ant-design/ant-design/pull/43803
`clientOnly` mark will only generate style in client side
> feat: add client mark

- src/hooks/useGlobalCache.tsx
fix https://github.com/ant-design/cssinjs/issues/127
ref https://github.com/ant-design/ant-design/issues/43510#issuecomment-1651129373
> fix: hmr should rebuild cache

- src/hooks/useCacheToken.tsx
- src/hooks/useEffectCleanupRegister.ts
- tests/index.spec.tsx
React 18 启用 `useInsertionEffect` 时，切换主题的场景下，样式会先于 token 写入 cache 并插入 dom，因此在某些场景下（比如这个 PR 的测试用例），最新的样式会被 token 卸载清除。
解法：把清除 token 样式的逻辑全部放在 `useEffect` 的 cleanup 方法中执行，这样会保证在渲染的最后执行清除逻辑。
> fix: should cleanup styles in useEffect cleanup function

- src/util.ts
- tests/util.spec.tsx
For large app, flatten token for each component will repeat called multiple times. Use WeakMap to cache the result:
> refactor: flattenToken use WeakMap

- src/hooks/useCacheToken.tsx
- src/hooks/useGlobalCache.tsx
- tests/index.spec.tsx
- tests/legacy.spec.tsx
修复组件重新 mount 时，插入的样式会被延后删除的问题。
事件顺序：
1. 组件卸载，将清除样式的任务放进下一次的 effect cleanup 中
2. 组件重新 mount，添加样式，发现 dom 中已存在，所以不会重复添加
3. 触发 effect cleanup，删除了已有样式，导致样式丢失。
解法：
注销样式前实时判断 cache 中是否存在。
> fix: style should not be removed when remounted

- src/Cache.ts
- src/hooks/useGlobalCache.tsx
> chore: opt the array creation

- src/transformers/legacyLogicalProperties.ts
- tests/__snapshots__/transform.spec.tsx.snap
- tests/transform.spec.tsx
fix: https://github.com/ant-design/ant-design/issues/47652
fix: https://github.com/ant-design/ant-design/issues/47707
> fix: logical attribute calc css variable logic error

- docs/examples/layer.tsx
- src/hooks/useStyleRegister.tsx
- tests/layer.spec.tsx
When set `layer`, the style except order should be append mode.
> fix: order of layer

- src/index.ts
- src/theme/calc/CSSCalculator.ts
- src/theme/calc/NumCalculator.ts
- src/theme/calc/calculator.ts
- src/theme/calc/index.ts
- src/theme/index.ts
- tests/calc.spec.tsx
`genCalc` API 由原 https://github.com/ant-design/ant-design/tree/master/components/theme/util/calc 迁移至 `@ant-design/cssinjs`
在 antd 中书写组件样式时，均统一使用 repo 中的 `genStyleHooks`、`mergeToken`、`genPresetColor`、`genSubStyleComponent`等 API，目前都统一存放于 https://github.com/ant-design/ant-design/tree/master/components/theme/util 目录下。
当前 antd 有类似`@ant-design/web3`、`@ant-design/x` 等生态库，在生态库中编写组件样式时目前几种选择：
1. 照搬 antd repo 中的代码至各生态库
2. 生态库内仅使用 `@ant-design/cssinjs` 简单实现类似的功能封装
3. 将可抽离的通用逻辑迁移至 `@ant-design/cssinjs` ，尽可能减少重复代码
对于方式一，并不可取，不同的库同样的代码，这会给后续的维护造成负担。
方式二，使用了当前已有的 `@ant-design/cssinjs` API，如 `useStyleRegister` 等，详见：https://github.com/ant-design/ant-design-web3/blob/main/packages/web3/src/theme/useStyle/index.ts
方式三，将通用的工具、逻辑抽离至 `@ant-design/cssinjs`，尽可能减少重复代码。该 RFC 仅迁移工具函数 `genCalc` 及其对应抽象类 …
> feat: add util genCalc and type AbstractCalculator

- docs/demo/first-render.md
- docs/examples/first-render.tsx
渲染了四万个 Button，耗时 700+ ms
可能的几个优化点：
1. findStyles。每次渲染组件都会执行 updateCSS，这里就会去 dom 遍历寻找是否有存在的 style 标签，耗时大头
2. flatternToken。每次 useToken 都会调用，里面有 hash 操作
3. spread。babel 的 pollyfill，看浏览器兼容性有 95%，不确定是否可以把产物 es 版本拉上去
> docs: add first render demo

- src/hooks/useGlobalCache.tsx
- tests/animation.spec.tsx
> R1 老师教我写代码
同时渲染 40000 个 Button，同一个组件，共用一份样式。
benchmark 比较极端，正常不太会这么写页面，但可以看出能节省很多时间。
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/e46aa61b-cced-4de1-89f4-0f78e8e1f692) | ![image](https://github.com/user-attachments/assets/b1d1d742-4bcf-423d-b8d7-60ac771a8ffb) |
在之前的逻辑里每个 Button 渲染的时候都会执行 `updateCSS`，这个方法会在 document 里遍历 style 标签。
现在做了一个缓存 Map，同一份样式在一个微任务期间只会执行一次 `updateCSS`。
> perf: cache effect
